import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SidebarBase from "@/_components/Sidebar/SidebarBase";

const plusJakarta = localFont({
  src: "../public/fonts/PlusJakartaSans-VariableFont_wght.ttf",
  variable: "--font-plus-jakarta",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kopikan POS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakarta.variable} antialiased`}>
        <main className="w-[1024px] px-4 flex justify-between gap-[22px] mx-auto my-0 shadow-lg">
          <SidebarBase />
          {children}
        </main>
      </body>
    </html>
  );
}
