import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SidebarBase from "./_components/Sidebar/SidebarBase";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kopikan POS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="w-[1024px] px-4 flex justify-between gap-[22px]">
          <SidebarBase />
          {children}
        </main>
      </body>
    </html>
  );
}
