import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "../../providers/ReactQueryProviders";

const plusJakarta = localFont({
  src: "../public/fonts/PlusJakartaSans-VariableFont_wght.ttf",
  variable: "--font-plus-jakarta",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kopikan POS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body
          className={`${plusJakarta.variable} antialiased flex justify-center`}
        >
          <main className="w-[768px] lg:w-[1024px] h-screen shadow-xl">
            {children}
          </main>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
